name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Configure Cargo for GitHub Packages
        run: |
          mkdir -p ~/.cargo
          cat >> ~/.cargo/config.toml << 'EOF'
          [registries.github]
          index = "sparse+https://github.com/matcharr/logwatcher.git"
          token = "${{ secrets.GITHUB_TOKEN }}"
          EOF

      - name: Publish to GitHub Packages
        run: |
          cargo publish --registry github
